# Generated by Django 3.1.3 on 2024-05-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20240505_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='nombreUsuario',
            new_name='username',
        ),
    ]
