# Generated by Django 3.1.3 on 2024-05-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20240505_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='username',
            new_name='nombreUsuario',
        ),
    ]


